<?php
// 전자공고 목록 페이지: JSON 파일을 읽어 제목, 작성일, 첨부 여부를 표시합니다.
$dataDir = __DIR__ . '/data';
$dataFile = $dataDir . '/notices.json';
if (!is_dir($dataDir)) { mkdir($dataDir, 0755, true); }
if (!file_exists($dataFile)) { file_put_contents($dataFile, '[]'); }
$notices = json_decode(file_get_contents($dataFile), true);
if (!is_array($notices)) { $notices = []; }
usort($notices, function ($a, $b) { return strcmp($b['created_at'] ?? '', $a['created_at'] ?? ''); });
function h($value) { return htmlspecialchars((string)$value, ENT_QUOTES, 'UTF-8'); }
?>
<!doctype html><html lang="ko"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0"><title>회사 공고 | KOREA IT</title><link rel="icon" href="../assets/favicon.svg"><link rel="stylesheet" href="../css/style.css"></head><body><header class="site-header"><div class="container header-inner"><a class="site-logo" href="../index.html"><img src="../assets/logo-horizontal-1200.png" alt="KOREA IT"></a><nav class="main-nav"><ul><li><a href="../index.html">Home</a></li><li><a href="../about/index.html">회사소개</a></li><li><a href="../services/index.html">서비스</a></li><li><a href="../assets-page/index.html">기술자산</a></li><li><a class="nav-notice active" href="index.php">공고</a></li><li><a href="../contact/index.html">문의</a></li></ul></nav><button class="menu-button" aria-expanded="false">메뉴</button></div><div class="mobile-menu"><ul><li><a href="../index.html">Home</a></li><li><a href="../about/index.html">회사소개</a></li><li><a href="../services/index.html">서비스</a></li><li><a href="../assets-page/index.html">기술자산</a></li><li><a href="index.php">공고</a></li><li><a href="../contact/index.html">문의</a></li></ul></div></header><main><section class="section"><div class="container"><p class="section-label">NOTICE</p><h1 class="section-title">회사 공고</h1><p class="section-lead">주식회사 코리아아이티의 전자공고 목록입니다.</p><p><a class="btn btn-secondary" href="admin.php">공고 등록</a></p><?php if (count($notices) === 0): ?><p class="notice-empty">등록된 공고가 없습니다.</p><?php else: ?><div class="notice-preview-list"><?php foreach ($notices as $notice): ?><a class="notice-preview-item" href="view.php?id=<?= h($notice['id'] ?? '') ?>"><strong><?= h($notice['title'] ?? '') ?></strong><span><?= h($notice['created_at'] ?? '') ?> · <?= !empty($notice['file_path']) ? '첨부 있음' : '첨부 없음' ?></span></a><?php endforeach; ?></div><?php endif; ?></div></section></main><footer class="site-footer"><div class="container"><p>© 2026 KOREA IT Co., Ltd.</p></div></footer><button class="to-top" aria-label="맨 위로 이동">↑</button><script src="../js/main.js"></script></body></html>
