<?php
// [파일 역할] 전자공고 목록 공개 페이지입니다. notices.json을 읽어 공고 목록을 표시합니다.
$dataFile = __DIR__ . '/data/notices.json';
if (!is_dir(__DIR__ . '/data')) { mkdir(__DIR__ . '/data', 0755, true); }
if (!file_exists($dataFile)) { file_put_contents($dataFile, '[]'); }
$notices = json_decode(file_get_contents($dataFile), true);
if (!is_array($notices)) { $notices = []; }
usort($notices, function ($a, $b) { return strcmp($b['created_at'] ?? '', $a['created_at'] ?? ''); });
function e($value) { return htmlspecialchars((string)$value, ENT_QUOTES, 'UTF-8'); }
?>
<!doctype html><html lang="ko"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0"><title>전자공고 | KOREA IT</title><link rel="stylesheet" href="../css/style.css"><link rel="icon" type="image/svg+xml" href="../assets/favicon.svg"></head><body>
<header class="site-header"><div class="container header-inner"><a class="site-logo" href="../index.html"><img src="../assets/logo-horizontal.svg" alt="KOREA IT"></a><nav class="main-nav"><ul><li><a href="../about/">회사소개</a></li><li><a href="../services/">서비스</a></li><li><a href="../erp/">운영 가능한 ERP</a></li><li><a href="../assets-page/">기술자산</a></li><li><a class="nav-notice" href="index.php">공고</a></li><li><a href="../contact/">문의</a></li><li><a class="nav-lang" href="../ja/">日本語</a></li></ul></nav><button class="menu-button" aria-expanded="false">메뉴</button></div><div class="mobile-menu"><ul><li><a href="../about/">회사소개</a></li><li><a href="../services/">서비스</a></li><li><a href="../erp/">운영 가능한 ERP</a></li><li><a href="../assets-page/">기술자산</a></li><li><a href="index.php">공고</a></li><li><a href="../contact/">문의</a></li><li><a href="../ja/">日本語</a></li></ul></div></header>
<main><section class="page-hero"><div class="container"><p class="hero-tag">OFFICIAL NOTICE</p><h1>전자공고</h1><p class="section-lead">주식회사 코리아아이티의 정관 및 관련 법령에 따른 공고 사항을 게시합니다.</p></div></section><section class="section"><div class="container"><p><a class="btn btn-secondary" href="admin.php">공고 관리자</a></p><?php if (count($notices) === 0): ?><div class="notice-empty">등록된 공고가 없습니다.</div><?php else: ?><table class="notice-table"><thead><tr><th>번호</th><th>제목</th><th>작성일</th><th>첨부</th></tr></thead><tbody><?php foreach ($notices as $i => $notice): ?><tr><td><?= count($notices) - $i ?></td><td><a href="view.php?id=<?= e($notice['id'] ?? '') ?>"><?= e($notice['title'] ?? '') ?></a></td><td><?= e($notice['created_at'] ?? '') ?></td><td><?= !empty($notice['file_path']) ? '있음' : '-' ?></td></tr><?php endforeach; ?></tbody></table><?php endif; ?></div></section></main><footer class="site-footer"><div class="container"><p>© 2026 KOREA IT Co., Ltd.</p></div></footer><button class="to-top" aria-label="맨 위로 이동">↑</button><script src="../js/main.js"></script></body></html>
